### ISSUE TITLE
"bii build" destroys eclipse project files

### ISSUE THREAD

**Issue by smessmer** [biicode/client#21]
OS: Ubuntu 14.10
Biicode 3.0

Steps to reproduce:

    $ mkdir cryfs
    $ cd cryfs
    $ bii init
    $ bii open messmer/cryfs
    $ bii cpp:configure -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug

Import project into eclipse: File -> Import -> Existing Projects Into Workspace.
There now is a "blocks" folder in the eclipse project containing the blocks

    $ bii build -- -j5

In eclipse: Right click on the project and select "Refresh". The "blocks" folder is gone.

    $ bii cpp:configure -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug

In eclipse: Refresh again. The "blocks" folder is there again.

Possibly related https://github.com/biicode/client/issues/22: when calling build, it re-configures the whole project.

**Comment by drodri** [comment]
I have checked in windows, with Eclipse Luna Service Release 1 (4.4.1), and it works ok. Not sure what could be, will check in Ubuntu, but all the Eclipse related code is supposed to be platform independent. What version of Eclipse are you running?

**Comment by smessmer** [comment]
Luna Service Release 1 (4.4.1) Build id: 20140925-1800.

**Comment by drodri** [comment]
I have tried in Ubuntu 14.04 with same Eclipse Luna, and didn't failed for me. Though I didnt try with gcc 4.9 (VM, running out of disk space) and build fails for cryfs, but other projects with the same workflow work OK and blocks folder is not removed from eclipse. Could you please check in your system if the behaviour is the same with a simple "Hello world" project? Thanks

**Comment by smessmer** [comment]
Still happens with biicode 3.1.1.

I narrowed it down to a minimal block (messmer/testblock). It seems to be connected to the

    INCLUDE(biicode/boost/setup)

in CMakeLists.txt. If I remove this line, it works.

**Comment by smessmer** [comment]
Did you have success reproducing it using my minimal testblock?

**Comment by drodri** [comment]
Hi! Sorry for the delay.
I have just tried, your minimal block really helped. I have tracked the problem down to a missbehavior in CMake only in Linux, it doesnt do that in Win. Basically CMake is overwriting innecessarily the .project Eclipse files even if there are no changes, overwriting the biicode config that loads blocks, etc. I think I have a fix, working on it, I will let you know, thanks!

**Comment by drodri** [comment]
I have pushed a fix to biicode develop branch, could you please check it? Tests are passing here, and working both in Win and also the failing Ubuntu behavior seems to work now.

**Comment by smessmer** [comment]
Hey, that's awesome. It seems to work. Thank you very much :)

**Comment by drodri** [comment]
Again, thanks to you :)
You are helping so much detecting, reporting and helping in debugging for
these bugs, so really appreciated.

Diego Rodriguez-Losada
CEO Biicode Innovation SL
M: +34 656274654

2015-05-11 21:11 GMT+02:00 Sebastian Meßmer <notifications@github.com>:
